version: "2"
services:
    backend:
        build: ./backend/
        ports: 
            - 3000:3000
        environment: 
            - NODE_ENV=develpment
            - PORT=3000
        volumes: 
            - ./backend:/app